---

- name: Import vars according to OS
  include_vars: "{{ ansible_os_family }}.yml"

- name: Sysctl setup
  include_tasks: sysctl.yml

- include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: crio.yml

- name: Install Kubernetes packages.
  package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  notify: restart kubelet
  with_items: "{{ kubernetes_packages }}"