---
- name: Ensure all packages are up to date
  yum:
    name: '*'
    state: latest
  args:
    update_cache: yes

- name: Disable SELinux
  selinux:
    state: disabled

- name: Diable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Add Kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes
    enabled: true
    gpgcheck: true
    baseurl: "{{ kubernetes_redhat_repo_base_url }}"
    gpgkey: "{{ kubernetes_redhat_repo_gpgkey }}"
    state: present