---
- name: Ensure all packages are up to date
  apt:
    upgrade: dist
    update_cache: yes
  
- name: Disable AppArmor
  command: systemctl disable apparmor
  ignore_errors: true

- name: Disable ufw
  command: systemctl disable ufw
  ignore_errors: true


- name: Install required packages
  apt:
    name: 
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: true

- name: Prepare apt keyring directory.
  file:
    path: "{{ kubernetes_apt_keyring | dirname }}"
    state: directory
    mode: 0755

- name: Get Kubernetes apt key.
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key"
    keyring: "{{ kubernetes_apt_keyring }}"
    state: present

- name: Add Kubernetes repository.
  apt_repository:
    repo: "deb [signed-by={{ kubernetes_apt_keyring }}] {{ kubernetes_apt_repository }} /"
    filename: pkgs_k8s_io
    state: present
    update_cache: true